### ISSUE TITLE
Support for OpenID Connect ID Tokens

### ISSUE THREAD

**Issue by alantbarlow** [angel-dart/oauth2#8]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/182.

**Comment by thosakwe** [comment]
If this is functionality you need, you’re more than welcome to send in a PR, but OpenID Connect is not necessarily on the priority list right now. If you are familiar with the OpenID specification, though, it should probably be pretty to implement on top of the AuthorizationServer class.
